### ISSUE TITLE
模组相关问题

### ISSUE THREAD

**Issue by fatinghenji** [GengGode/GenshinImpactNaturalLaw#3]
模组指的是什么呢？是您的另一个自动地图吗？
不是的话哪里可以下载模组呢？

**Comment by GengGode** [comment]
是的，需要在
![image](https://user-images.githubusercontent.com/47711102/128632784-a7a145cf-8683-429b-be3d-a7ea641a6db2.png)
文件夹中
释放地图的release到
![image](https://user-images.githubusercontent.com/47711102/128632827-fe30e914-8476-4adc-ad4c-2671fa883dae.png)
![image](https://user-images.githubusercontent.com/47711102/128632851-8cf04d41-1875-4564-aa0f-46095970dd10.png)
参考这样的目录结构
然后在启动器中刷新模组即可
![image](https://user-images.githubusercontent.com/47711102/128632890-4105df78-2c6f-4050-ae1f-6db077ebc176.png)

**Comment by GengGode** [comment]
因为个人技术原因，我还不太清楚如何多个库合并一起发布
